### ISSUE TITLE
topicsページのレイアウト調整

### ISSUE THREAD

**Issue by kogepanh** [Kenny-NISLab/nisweb#9]
topics ページ（記事）内のレイアウト検討・調整をお願いします

- list のチョボをつけて欲しい （例：https://main.d1jykvfvee0tf5.amplifyapp.com/topics/7mAtnC2r68qffqET0tZi0C）
- title 下部に日付を表示して欲しい
- title は太字の方がわかりやすい？
- 外部リンクは別タブで開くようにしてほしい（面倒なら、topics内のリンクは全て別タブで開くようにするのでもいいかも）
- topics 一覧から検索する際に、ドロップダウンメニューに「全て」みたいな選択肢があるとよいかも
- 記事下部の「記事一覧」リンクの左右に前後記事へのリンク（できればタイトルと矢印が表示されるように）があるとよいかも
- サイドバーに「最近の投稿（10件くらい？）」と「年度別」「カテゴリ別」があるとよいかも

**Comment by kogepanh** [comment]
Contentful側のMarkdownで、画像の上下に空白の改行を入れてないと、<p>タグの内部に<img>が入っちゃうから、imgの上下には最低のmarginを取っといた方がよさそう。

h3タグの表示とかはContentful書く人の問題やけど、imgの上下の改行はフロントの表示側でも対応できる範囲やし、念のため設定しといた方がよさそう

**Comment by nkthkr** [comment]
画像の上下に空白がないのはそもそもマークダウンの記法として間違ってない？

**Comment by kogepanh** [comment]
間違ってる！
けど、Contentful側のプレビューでそれに気付ける方法がないから、念のためフロント側で制御しといた方がいいんかなーと思って
佐藤先生もページ更新しはるから、念のため？笑
まあでも記法としてよろしくないから、フロント側では対処せず、Contentfulのドキュメントとして明記するのでもいいと思う！

**Comment by nkthkr** [comment]
headingに関しても同じやけどサイトの品質を保つためには逆に実際のページ見て気付けるようにしといた方が修正できる(表示上問題ないようにしてると誰も一生気づかない)からその方がいいんかなあとは思うけどどっちの方針でいこ

**Comment by kogepanh** [comment]
それはもう間違い無くて、真意よな笑
個人的な意見としてはヒカルと同意見。
やし、現状のまま、ちゃんとMarkdownを書く方向でいきますか！

**Comment by nkthkr** [comment]
おけい、とりあえずli等のこっち側の問題の開発終わったらそれぞれ移行した記事を本番環境で確認するまでやってもらおか

**Comment by kogepanh** [comment]
了解！
